#!/usr/bin/env bash
#A bash script that displays a list of current running processes
#It shows all processes for all users, including those which might
#not have a TTY
#Shows process hierarchy
ps -aux --forest
