#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond"
#+ indefinitely with a sleep 2 in between each iteration.
# A Bash script that displays "I am invincible!!!" between 
#+ each iteration

while true
do
	echo  "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
