#!/usr/bin/env bash
#This Bash script will displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

num=0
while [ $num -lt 11 ]
do
	if [ $num = 9 ]
		then 
		echo "Hi"
	else
		echo "Best School"
	fi
	((num=num+1))
done
