#!/usr/bin/env bash
#This is a Bash script that loops from 1 to 10 and displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iterations

COUNTER=1
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 4 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((COUNTER+=1))
done
