#!/usr/bin/env bash
#prints 'Best School' 10 times
i=0
while [ $i -le 19 ]
do
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		esac
	
	i=$((i + 1))
	echo $i
			
done
