#!/usr/bin/env bash
#This is a Bash script that displays numbers from 1 to 20 with some features

COUNTER=1
while [ $COUNTER -lt 21 ]
do
    case $COUNTER in

        4)
	    echo $COUNTER
	    echo "bad luck from China"
	    ;;
	
	9)
	    echo $COUNTER
	    echo "bad luck from Japan"
	    ;;
	
	17)
	    echo $COUNTER
	    echo "bad luck from Italy"
	    ;;

	*)
	    echo $COUNTER
	    ;;
    esac

    ((COUNTER+=1))
done
