#!/usr/bin/env bash
# configure nginx server to run as nginx server
chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
