#!/usr/bin/env bash
# creates a group 'nginx' with chown and runs nginx as user 'nginx'

chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/site-available/default
sudo -i nginx service nginx start
