#!/usr/bin/env bash
# runs nginx as user 'nginx'
pkill apaache 
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etx/nginx/sites-available/default
sudo -u nginx service nginx start
